"""Add "completed" column to table

Revision ID: 5f0f5ec60e23
Revises: 27d2b27cff6a
Create Date: 2022-08-02 20:58:50.243399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f0f5ec60e23'
down_revision = '27d2b27cff6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('completed', sa.Boolean(), nullable=True))

    op.execute('UPDATE tasks SET completed = False WHERE completed IS NULL')

    op.alter_column('tasks', 'completed', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'completed')
    # ### end Alembic commands ###
