"""Remove "completed" column

Revision ID: 0029b997b53e
Revises: cecad07ce7c8
Create Date: 2022-08-04 15:11:31.383998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0029b997b53e'
down_revision = 'cecad07ce7c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'completed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.execute('UPDATE tasks SET completed = False WHERE completed IS NULL')
    op.alter_column('tasks', 'completed', nullable=False)
    # ### end Alembic commands ###
