"""Add "completed" column to table

Revision ID: cecad07ce7c8
Revises: 581b8573496b
Create Date: 2022-08-03 22:11:06.742860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cecad07ce7c8'
down_revision = '581b8573496b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('completed', sa.Boolean(), nullable=True))

    op.execute('UPDATE tasks SET completed = False WHERE completed IS NULL')

    op.alter_column('tasks', 'completed', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'completed')
    # ### end Alembic commands ###
