"""Add new table and model one to one relationship

Revision ID: 5598b465ddbc
Revises: f684c2a29290
Create Date: 2022-08-06 07:12:30.274886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5598b465ddbc'
down_revision = 'f684c2a29290'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todolists',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('todos', sa.Column('todolist_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'todos', 'todolists', ['todolist_id'], ['id'])

    op.execute('''
    UPDATE todolists 
    SET id = 1, 
    name = 'List 1'
    WHERE id IS NULL
    ''')

    op.alter_column('todolists', 'id', nullable=False)
    op.alter_column('todolists', 'name', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todos', type_='foreignkey')
    op.drop_column('todos', 'todolist_id')
    op.drop_table('todolists')
    # ### end Alembic commands ###
