"""Update list nullable status

Revision ID: 719398a8a176
Revises: 5598b465ddbc
Create Date: 2022-08-06 07:41:31.280965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '719398a8a176'
down_revision = '5598b465ddbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('update todos set todolist_id = 1 where todolist_id is null')
    op.alter_column('todos', 'todolist_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'todolist_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
